# Generated by Django 4.2.7 on 2023-11-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_deleted_at'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='articles',
            field=models.ManyToManyField(related_name='articles', to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='shipments.carriers'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
